version: '20.10.21'


services:
  yacut:
       build: ../
       restart: always
       depends_on:
         - db
       env_file:
         - ../.env

  db:
    image: postgres:13.0-alpine
    volumes:
      - my_db:/var/lib/postgresql/data/
    env_file:
      - ../.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../yacut/static/:/var/html/static/
    depends_on:
      - yacut


volumes:
  my_db: